const fs = require('fs');
let content = fs.readFileSync('src/pages/MarketingScripts.tsx', 'utf8');

// Ensure new icons are imported safely
if (content.includes('lucide-react";')) {
    content = content.replace(/lucide-react";/, 'Car, MessageSquare, HelpCircle, Zap } from "lucide-react";');
}

const NEW_THEMES = `,
  {
    theme: "Driving Safety",
    icon: Car,
    color: "bg-yellow-100 text-yellow-700 border-yellow-200",
    accent: "#eab308",
    videos: [
      { title: "The Midnight Blur", s1: "Kikki sitting in a driver's seat, rubbing her eyes with open palms while looking forward. \\"Night driving in Accra is stressful enough, but when the streetlights blur, the danger doubles. Poor vision is a silent crash risk.\\"", s2: "Frederick standing confidently outdoors in a medium shot. \\"Don't gamble with your eyesight on the highway. Use the MedPharma app to book an eye check-up instantly. See clearly, drive safely.\\"" },
      { title: "The Heavy Eyes", s1: "Kikki stretching her neck slowly in a car seat, looking exhausted. \\"You think you can push through driver fatigue with just another energy drink, but microsleeps happen in a fraction of a second.\\"", s2: "Frederick holding a smartphone at chest level. \\"Rest is your only true defense. But if constant fatigue is haunting you, book a quick teleconsultation on MedPharma to check for underlying health issues.\\"" },
      { title: "The Hidden Drowsiness", s1: "Kikki looking at a small medicine box in her open palm. \\"You popped an allergy pill before your road trip, not realizing it causes severe drowsiness. Side effects don't care about your destination.\\"", s2: "Frederick gesturing slowly with one open hand. \\"Always know what you are taking before you drive. Chat with a licensed MedPharma pharmacist directly through the app to verify your medication side effects.\\"" },
      { title: "The Distracted Glance", s1: "Kikki holding a phone down at her side, looking briefly down then up. \\"Looking at your phone for just three seconds at highway speed means driving blind for almost a hundred meters.\\"", s2: "Frederick standing calmly, hands relaxed at his sides. \\"Keep your eyes on the road. If you need healthcare on the go, the MedPharma app will be waiting for you safely when you park.\\"" },
      { title: "The Sudden Blowout", s1: "Kikki standing by a car wheel, looking concerned. \\"Tire blowouts are terrifying and often cause panic. The shock alone can trigger severe anxiety or blood pressure spikes on the highway.\\"", s2: "Frederick looking directly at the camera with a reassuring posture. \\"Stay calm, steer straight, and brake slowly. And remember, if the shock affects your health, a MedPharma doctor is just a video call away.\\"" },
      { title: "The Highway Dehydration", s1: "Kikki wiping her forehead slowly, looking tired. \\"Long drives in the hot sun drain your body of water. Dehydration causes confusion and slows your reaction time on the road.\\"", s2: "Frederick holding a water bottle at waist level. \\"Keep water in your car and take breaks. If you feel dizzy, pull over immediately. MedPharma delivers rehydration salts to your location if you need them.\\"" },
      { title: "The Glare Blindness", s1: "Kikki shielding her eyes with a flat palm. \\"The intense afternoon sun bouncing off the road can blind you for crucial seconds. Glare is a major factor in highway accidents.\\"", s2: "Frederick standing in soft lighting. \\"Protect your vision. Wear polarized sunglasses while driving, and use MedPharma to book an annual vision test to keep your eyes sharp.\\"" },
      { title: "The Commuter's Backache", s1: "Kikki holding her lower back slowly with one hand. \\"Sitting in endless traffic every single day ruins your posture. That lingering lower back pain makes driving unbearable.\\"", s2: "Frederick gesturing gently with an open palm. \\"Adjust your seat for proper support. If the pain persists, consult a physiotherapist virtually through the MedPharma app right from your home.\\"" },
      { title: "The Rush Hour Stress", s1: "Kikki taking a deep, heavy breath, looking frustrated. \\"Road rage and endless gridlock do more than ruin your mood. Chronic traffic stress slowly raises your blood pressure.\\"", s2: "Frederick standing calmly, exuding peace. \\"Take deep breaths and prioritize your cardiovascular health. Book routine heart check-ups with MedPharma to ensure the daily commute isn't damaging your heart.\\"" },
      { title: "The Emergency Kit", s1: "Kikki looking into an empty car trunk. \\"Most drivers have a spare tire, but almost nobody carries a proper first aid kit. When a roadside emergency happens, you are left stranded.\\"", s2: "Frederick holding a small, neat medical box at chest level. \\"Be prepared for anything. Order a fully stocked premium first aid kit directly from the MedPharma app and keep it in your trunk.\\"" }
    ]
  },
  {
    theme: "MedPharma Testimonials",
    icon: MessageSquare,
    color: "bg-emerald-100 text-emerald-700 border-emerald-200",
    accent: "#10b981",
    videos: [
      { title: "The Midnight Save", s1: "Kikki looking relieved, standing in a softly lit room. \\"My daughter's fever spiked at midnight. Every pharmacy in our neighborhood was closed, and I was terrified.\\"", s2: "Frederick nodding with a warm smile. \\"We hear this every day. That is why MedPharma delivers essential medications directly to your door, safely and securely, no matter the hour.\\"" },
      { title: "The Routine Care Peace of Mind", s1: "Kikki smiling gently, holding a neatly wrapped box. \\"Managing my daily hypertension medication used to be a hassle. I was always forgetting to refill until the bottle was empty.\\"", s2: "Frederick standing with excellent posture. \\"With FulLife, we automate your routine medications. We remember so you do not have to, delivering your refills exactly when you need them.\\"" },
      { title: "The Instant Doctor", s1: "Kikki looking relaxed in a home setting. \\"I was too weak to leave the house and face the clinic queues. I thought I would have to just wait out the pain.\\"", s2: "Frederick holding a tablet at chest height. \\"Our teleconsultation feature brings the doctor to you. A simple video call gets you a diagnosis and a prescription sent straight to your home.\\"" },
      { title: "The Authentic Guarantee", s1: "Kikki holding a generic medicine box with a skeptical look. \\"Buying medication from random vendors always left me worried. You hear so many stories about fake drugs on the market.\\"", s2: "Frederick speaking with authority and calm. \\"Your safety is our top priority. Every single drug on MedPharma is one hundred percent authentic, verified by licensed Ghanaian pharmacists.\\"" },
      { title: "The Office Delivery", s1: "Kikki in an office setting, looking pleased. \\"I had back-to-back meetings all week. There was absolutely no time to run to the pharmacy during my lunch break.\\"", s2: "Frederick gesturing openly. \\"MedPharma respects your time. We deliver your prescriptions directly to your office desk seamlessly, so you can stay focused on your work.\\"" },
      { title: "The Lab Test at Home", s1: "Kikki sitting comfortably on a couch. \\"I needed a routine blood test but kept postponing it because the laboratory is always so crowded in the mornings.\\"", s2: "Frederick smiling confidently. \\"Healthcare should fit into your schedule. MedPharma allows you to book certified lab technicians who come to your home to take samples comfortably.\\"" },
      { title: "The Parent's Relief", s1: "Kikki smiling with a warm, motherly expression. \\"Living in another city meant I could not check on my mother's medications easily. I was always worried she was missing doses.\\"", s2: "Frederick nodding approvingly. \\"Distance should never compromise care. With MedPharma, you can manage and pay for your family's routine medications from anywhere in the world.\\"" },
      { title: "The Quick Upload", s1: "Kikki holding up a piece of paper, smiling. \\"I left the hospital with a handwritten prescription and did not want to hunt for a pharmacy in traffic.\\"", s2: "Frederick holding a smartphone. \\"Just snap a photo. Upload your prescription to the MedPharma app, and our team will process, pack, and deliver it straight to your door.\\"" },
      { title: "The Corporate Benefit", s1: "Kikki in business attire, looking proud. \\"Since our company switched to MedPharma for our health benefits, employee satisfaction has completely skyrocketed.\\"", s2: "Frederick wearing a clean blazer. \\"A healthy team is a productive team. MedPharma provides seamless B2B healthcare solutions that actually add value to your employees' daily lives.\\"" },
      { title: "The Privacy Priority", s1: "Kikki looking discreet and comfortable. \\"I needed to buy sensitive personal care products, and I really did not want to face the awkward pharmacy counter interactions.\\"", s2: "Frederick speaking with a reassuring tone. \\"Your privacy matters. MedPharma delivers your health and wellness products in discreet packaging, ensuring total confidentiality every single time.\\"" }
    ]
  },
  {
    theme: "MedPharma Q&A",
    icon: HelpCircle,
    color: "bg-indigo-100 text-indigo-700 border-indigo-200",
    accent: "#6366f1",
    videos: [
      { title: "How fast is delivery?", s1: "Kikki looking directly at the camera with a curious expression. \\"The biggest question everyone asks is: when I order my medication on the app, how fast does it actually arrive?\\"", s2: "Frederick smiling confidently. \\"We move fast. We offer same-day delivery anywhere within Accra, and reliable next-day delivery for locations nationwide.\\"" },
      { title: "Are the drugs real?", s1: "Kikki leaning in slightly, asking a serious question. \\"With so many fake products out there, how can I be absolutely certain that the drugs from MedPharma are authentic?\\"", s2: "Frederick standing firm and professional. \\"We source exclusively from certified, verified distributors. Every single product is inspected by our licensed pharmacists before it ever reaches you.\\"" },
      { title: "How do I book a doctor?", s1: "Kikki holding her phone in a relaxed manner. \\"I need to speak to a doctor today, but I don't know how complicated the booking process is on the app.\\"", s2: "Frederick holding a tablet at chest level. \\"It takes less than two minutes. Open the app, select Teleconsultation, choose your preferred time, and a licensed doctor will connect with you via video.\\"" },
      { title: "Do you take insurance?", s1: "Kikki looking inquisitive. \\"Private healthcare can be expensive. Do you accept private health insurance to cover my medication and consultation costs?\\"", s2: "Frederick nodding clearly. \\"Yes, we partner with major private health insurance providers in Ghana. You can link your policy directly in the app for seamless cashless transactions.\\"" },
      { title: "What are the payment methods?", s1: "Kikki holding a bank card casually at her side. \\"I prefer using Mobile Money, but my husband likes using his Visa card. What payment options do you actually support?\\"", s2: "Frederick gesturing with an open palm. \\"We support everything you need. You can pay securely via Mobile Money, debit or credit card, or your linked health insurance policy directly in the app.\\"" },
      { title: "Can I get prescription refills?", s1: "Kikki looking thoughtfully at the camera. \\"I take the same blood pressure medication every single month. Do I really have to manually order it every time?\\"", s2: "Frederick smiling warmly. \\"Not at all. With our FulLife program, you set it up once, and we automatically process and deliver your routine refills every month.\\"" },
      { title: "What if I have a question about my dose?", s1: "Kikki looking slightly confused. \\"Sometimes I forget if I should take my medication before or after meals. Who can I ask if I am already at home?\\"", s2: "Frederick looking reassuring. \\"You are never alone. You can use the in-app chat to speak with our AI health assistant, Kobikuul, or connect directly to a human pharmacist for instant advice.\\"" },
      { title: "Are lab tests accurate at home?", s1: "Kikki raising a polite question. \\"I love the idea of home lab tests, but are the results just as accurate as walking into a big hospital laboratory?\\"", s2: "Frederick speaking with authority. \\"Absolutely. We dispatch certified phlebotomists to draw your samples, which are then processed in top-tier accredited partner laboratories for perfect accuracy.\\"" },
      { title: "Can you deliver to my village?", s1: "Kikki looking hopeful. \\"My grandmother lives outside the main capital city. Can MedPharma still reach her with her monthly medications?\\"", s2: "Frederick nodding with a smile. \\"Yes, we can. While we offer same-day delivery in Accra, our logistics network handles secure nationwide delivery to ensure everyone gets their care.\\"" },
      { title: "Is my medical data safe?", s1: "Kikki looking serious. \\"I am uploading my private medical prescriptions and talking to doctors on my phone. How secure is my personal health data?\\"", s2: "Frederick maintaining a calm, serious posture. \\"We use bank-level encryption. Your health records, consultation videos, and prescriptions are strictly confidential and protected by world-class security protocols.\\"" }
    ]
  },
  {
    theme: "Youth Segments",
    icon: Zap,
    color: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    accent: "#d946ef",
    videos: [
      { title: "The Burnout Hustle", s1: "Kikki looking exhausted, rubbing her temples slowly. \\"Hustle culture tells you to grind all night, but running on three hours of sleep and pure caffeine is destroying your immune system.\\"", s2: "Frederick speaking warmly but firmly. \\"Burnout is real. Prioritize your recovery. MedPharma delivers premium multivitamins and wellness supplements to help rebuild your energy the healthy way.\\"" },
      { title: "TikTok Skincare Hacks", s1: "Kikki looking skeptically at a small unmarked jar. \\"Mixing random kitchen ingredients on your face because a viral video told you to is a quick way to ruin your skin barrier.\\"", s2: "Frederick gesturing calmly. \\"Trust science, not trends. Book a teleconsultation with a verified dermatologist on MedPharma and get clinically approved skincare delivered to your door.\\"" },
      { title: "The Screen Time Strain", s1: "Kikki rubbing her eyes gently, looking away from a screen. \\"Between laptops at work and scrolling on your phone all night, eye strain is the modern headache we all ignore.\\"", s2: "Frederick standing calmly. \\"Protect your vision. Practice the twenty-twenty rule, and use the MedPharma app to order lubricating eye drops to keep your eyes healthy.\\"" },
      { title: "The Period Cramp Paralysis", s1: "Kikki sitting quietly, looking uncomfortable. \\"When severe period cramps hit, the last thing you want to do is get dressed and walk to a pharmacy in the hot sun.\\"", s2: "Frederick speaking with a kind, professional tone. \\"Stay in bed and get comfortable. Order your pain relief and feminine care products on MedPharma, and we will bring them right to you.\\"" },
      { title: "The Fake Supplement Trap", s1: "Kikki looking closely at a flashy protein powder bottle. \\"Buying fitness supplements from unverified online vendors is a huge gamble. You never really know what you are putting in your body.\\"", s2: "Frederick standing confidently. \\"Your fitness journey deserves safe fuel. MedPharma guarantees one hundred percent authentic sports nutrition and vitamins, sourced directly from verified manufacturers.\\"" },
      { title: "The Anxiety Spiral", s1: "Kikki taking a deep, slow breath, looking overwhelmed. \\"Trying to balance your career, social life, and family expectations can quietly push your mental health to the edge.\\"", s2: "Frederick looking reassuring and calm. \\"It is okay to ask for help. Use the MedPharma app to book a discreet teleconsultation with a mental health professional from the safety of your room.\\"" },
      { title: "The Gym Injury Ignore", s1: "Kikki holding her shoulder gently, wincing slightly. \\"Pushing through sharp joint pain at the gym because you think you are tough will only bench you for six months later.\\"", s2: "Frederick gesturing slowly. \\"Listen to your body. If the pain is sharp, stop. Order muscle relaxants and anti-inflammatories on MedPharma to start your recovery immediately.\\"" },
      { title: "The Energy Drink Crash", s1: "Kikki looking drained, staring blankly ahead. \\"Chugging energy drinks gives you a fast spike, but the afternoon sugar crash leaves you feeling worse than before you started.\\"", s2: "Frederick holding a glass of water. \\"Real energy comes from hydration and proper nutrition. Find doctor-approved daily multivitamins on MedPharma that build sustainable energy without the crash.\\"" },
      { title: "The Self-Diagnosis Panic", s1: "Kikki scrolling on her phone, looking increasingly worried. \\"Googling your symptoms at two in the morning will convince you that a simple headache is a rare terminal disease.\\"", s2: "Frederick smiling gently. \\"Step away from the search bar. Use the MedPharma app to chat with our AI health assistant, Kobikuul, for safe, rational medical guidance anytime.\\"" },
      { title: "The Post-Party Dehydration", s1: "Kikki holding her head lightly, eyes closed. \\"A great weekend out is fun until the Sunday morning headache hits. Severe dehydration is the real reason you feel terrible.\\"", s2: "Frederick standing calmly. \\"Recovery starts with hydration. MedPharma delivers oral rehydration salts and pain relief directly to your door, so you can bounce back fast.\\"" }
    ]
  }
];`;

content = content.replace(/];/, NEW_THEMES);
fs.writeFileSync('src/pages/MarketingScripts.tsx', content, 'utf8');
console.log('Successfully injected themes');
